<div class="colunm_row md" style="max-width: 100%" data-mce-style="max-width: 100%">
    <table class="content_column md_mx mce-item-table" align="center" border="0" cellspacing="0" cellpadding="0" width="100%" style="text-align: center;-webkit-text-size-adjust: 100%;-ms-text-size-adjust: 100%;mso-table-lspace: 0pt;mso-table-rspace: 0pt;" data-mce-style="text-align: center;-webkit-text-size-adjust: 100%;-ms-text-size-adjust: 100%;mso-table-lspace: 0pt;mso-table-rspace: 0pt;">
        <tbody>
            <tr>
                <td class="column_cell md_px" style="-webkit-text-size-adjust: 100%;-ms-text-size-adjust: 100%;mso-table-lspace: 0pt;mso-table-rspace: 0pt;padding: 20px 20px;" data-mce-style="-webkit-text-size-adjust: 100%;-ms-text-size-adjust: 100%;mso-table-lspace: 0pt;mso-table-rspace: 0pt;padding: 20px 20px;">
                    <table class="content_column md_mx mce-item-table" align="center" border="0" cellspacing="0" cellpadding="0" width="100%" style="text-align: center;-webkit-text-size-adjust: 100%;-ms-text-size-adjust: 100%;mso-table-lspace: 0pt;mso-table-rspace: 0pt;" data-mce-style="text-align: center;-webkit-text-size-adjust: 100%;-ms-text-size-adjust: 100%;mso-table-lspace: 0pt;mso-table-rspace: 0pt;">
                        <tbody>
                            <tr>
                                <td class="column_cell md_px" style="-webkit-text-size-adjust: 100%;-ms-text-size-adjust: 100%;mso-table-lspace: 0pt;mso-table-rspace: 0pt;padding: 0px " data-mce-style="-webkit-text-size-adjust: 100%;-ms-text-size-adjust: 100%;mso-table-lspace: 0pt;mso-table-rspace: 0pt;padding:0px;">
                                    <p class="text_lead text_secondary mb_md" style="margin-top: 0px; margin-bottom: 20px; word-break: break-word; text-align: left; line-height: 26px" data-mce-style="color: #333333; font-family: Arial; margin-top: 0px; margin-bottom: 20px; word-break: break-word; font-size: 16px; text-align: left; line-height: 26px"><span style="text-align: center; font-size: 16px;" data-mce-style="text-align: center; font-size: 16px;"><span style="color: #333333; font-family: Arial;" data-mce-style="color: #333333; font-family: Arial;">Please use the below OTP (sent on your request) to change the Password.</span></span>
                                    </p>
                                    <p class="text_lead text_secondary mb_md" style="margin-top: 0px; margin-bottom: 20px; word-break: break-word; text-align: left; line-height: 26px" data-mce-style="color: #333333; font-family: Arial; margin-top: 0px; margin-bottom: 20px; word-break: break-word; font-size: 16px; text-align: left; line-height: 26px"><span style="text-align: center; font-size: 16px;" data-mce-style="text-align: center; font-size: 16px;"><span style="color: #333333; font-family: Arial;" data-mce-style="color: #333333; font-family: Arial;"> <strong>OTP:</strong> <?= $model['otp'] ?></span></span>
                                    </p>
                                    <p class="text_lead text_secondary mb_md" style="margin-top: 0px; margin-bottom: 20px; word-break: break-word; text-align: left; line-height: 26px" data-mce-style="color: #333333; font-family: Arial; margin-top: 0px; margin-bottom: 20px; word-break: break-word; font-size: 16px; text-align: left; line-height: 26px"><span style="text-align: center; font-size: 16px;" data-mce-style="text-align: center; font-size: 16px;"><span style="color: #333333; font-family: Arial;" data-mce-style="color: #333333; font-family: Arial;">Please note: this OTP will only be valid for <?= $model['duration'] ?> minutes.</span></span>
                                    </p>
                                    <p class="text_lead text_secondary mb_md" style="margin-top: 0px; margin-bottom: 20px; word-break: break-word; text-align: left; line-height: 26px" data-mce-style="color: #333333; font-family: Arial; margin-top: 0px; margin-bottom: 20px; word-break: break-word; font-size: 16px; text-align: left; line-height: 26px"><span style="text-align: center; font-size: 16px;" data-mce-style="text-align: center; font-size: 16px;"><span style="color: #333333; font-family: Arial;" data-mce-style="color: #333333; font-family: Arial;">We advise you to frequently change the password by clicking 'Settings' on your OPAL USP Dashboard.</span></span>
                                    </p>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </td>
            </tr>