
<table width="100%" cellspacing="0" cellpadding="0" border="0" style="background:rgb(226, 234, 240) none repeat scroll 0% 0% / auto padding-box border-box;"><tbody><tr><td align="center"><div style="margin:0 auto;width:600px;padding:0px"><meta charset="UTF-8">
<style>
@import url('https://fonts.googleapis.com/css2?family=Cairo:wght@400;500;600;700&display=swap');
     .column_cell a:visited {
       color: #fff;
	 }
	 .column_cancel a:visited{
		color: #f71b02;
	 }
	 a,a:visited {
		color:#4ca0ab;
	 }
</style>

<table width="100%" style="background: none 0% 0% / auto repeat scroll padding-box border-box rgb(226, 234, 240); border-spacing: 0px; border-collapse: collapse; text-size-adjust: 100%;">
	<tbody>
        <tr>
            <td width="600" align="center" style="background: rgb(226, 234, 240); margin: 0px auto; width: 600px; max-width: 600px; padding: 0px; border-collapse: collapse; text-size-adjust: 100%;" data-mce-href="background:rgb(226, 234, 240);margin:0 auto;width:600px;max-width: 600px;padding:0px">
            <div style="background:rgb(226, 234, 240);margin:0 auto;width:600px;padding: 0px" data-mce-href="background:rgb(226, 234, 240);margin:0 auto;width:600px;padding:0px">
                <table style="border-spacing: 0px; border-collapse: collapse; text-size-adjust: 100%;">
                    <tbody>
                        <tr>
                            <td align="center" width="600" style="margin-top: 50px; max-width: 600px; text-align: center; width: 600px; border-collapse: collapse; text-size-adjust: 100%;" data-mce-style="margin-top:50px;max-width: 600px;width:600px; text-align: center">
                                <!-- PRE-HEADER TEXT --><span class="preheader" style="font-size: 16px;font-family: cairo;padding-top: 30px; display:none!important;visibility:hidden;opacity:0;color:transparent;height:0;width:0;width: 600px;word-break: break-word;max-width:600px;" data-mce-style="font-size: 16px;font-family: cairo;padding-top: 30px;display: none !important; visibility: hidden; opacity: 0; color: transparent; height: 0;max-width:600px;width: 600px;word-break: break-word;">A Supplier has registered on JSRS</span>
                            </td>
                        </tr>
                    </tbody>
                </table>
                    <table class="content_section mce-item-table" role="presentation" align="center" width="600" cellspacing="0" cellpadding="0" border="0" style="max-width: 600px; width: 600px; margin-left: auto; margin-right: auto; background-color: rgb(226, 234, 240); text-size-adjust: 100%; border-spacing: 0px; border-collapse: collapse;" data-mce-style="width:600px;max-width: 600px; margin-left: auto; margin-right: auto; background-color: #e2eaf0; -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt;">
                        <tbody>
                            <tr>
                                <td class="column_cell px py_xs text_right mobile_center" style="vertical-align: top; text-align: right; margin-bottom: 25px; margin-top: 25px; text-size-adjust: 100%; float: right; width: 50%; padding: 25px 0px; border-collapse: collapse;" data-mce-style="vertical-align: top; text-align: right; margin-bottom: 25px; margin-top: 25px; -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt; float: right; width: 50%; padding: 25px 0px 25px 0px;">
                                        <p class="text_secondary" style="color: rgb(149, 155, 160); font-family: cairo; margin-top: 0px; margin-bottom: 0px; word-break: break-word; font-size: 16px; line-height: 26px; margin-right: 20px; text-size-adjust: 100%;" data-mce-style="color: #959ba0; font-family: cairo; margin-top: 0px; margin-bottom: 0px; word-break: break-word; font-size: 16px; line-height: 26px; margin-right: 20px;"><a href="http://192.168.1.53/rabt/api/web/mails/166684917284.html" style="text-size-adjust: 100%; text-decoration: none; color: rgb(3, 102, 214); font-family: cairo; margin-top: 0px; margin-bottom: 0px; word-break: break-word; font-size: 13px; line-height: 26px; overflow-wrap: break-word;" data-mce-href="http://192.168.1.53/rabt/api/web/mails/166684917284.html" data-mce-style="-webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; text-decoration: none; color: #0366d6 !important; font-family: cairo; margin-top: 0px; margin-bottom: 0px; word-break: break-word; font-size: 13px; line-height: 26px;">View in browser</a></p>
                                </td>
                            </tr>
                                <tr>
                                    <td class="content_cell bg_white brounded bt_primary px py_md" style="font-size: 0px; text-align: center; border-bottom: 1px solid rgb(218, 218, 218); background-color: rgb(247, 247, 247); border-top: 4px solid rgb(76, 160, 171); border-radius: 4px; text-size-adjust: 100%; padding: 10px 0px; border-collapse: collapse;" data-mce-style="font-size: 0; text-align: center; border-bottom: 1px solid #dadada; background-color: #f7f7f7; border-top: 4px solid #4ca0ab; border-radius: 4px; -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt; padding: 10px 0px 10px 0px;">
                                        <div style="background: #f7f7f7;" data-mce-style="background: #f7f7f7;">
                                            <table class="column_row mce-item-table" style="font-size: 0px; text-align: center; max-width: 100%; margin-left: 0px; margin-right: 0px; width: 100%; border-spacing: 0px; border-collapse: collapse; text-size-adjust: 100%;" data-mce-style="font-size: 0; text-align: center; max-width: 100%; margin-left: 0; margin-right: 0; width: 100%;">
                                                <tbody>
                                                    <tr style="display: flex; align-items: center; justify-content:space-evenly;" data-mce-style="display: flex; align-items: center; justify-content:space-evenly;">
                                                        <td class="column_cell px py_xs text_primary text_left mobile_center" style="vertical-align: top; text-align: center; text-size-adjust: 100%; padding: 10px 0px; border-collapse: collapse;" data-mce-style="vertical-align: top; text-align: center; -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt; padding: 25px 0px 25px 0px;"><img src="http://192.168.1.53/rabt/backend/assets/images/mail/img/newheaderrabtlogo.png" alt="rabtlogo" style="-ms-interpolation-mode: bicubic; border: 0; height: auto; line-height: 100%; outline: none; text-decoration: none;" data-mce-src="http://192.168.1.53/rabt/backend/assets/images/mail/img/newheaderrabtlogo.png" data-mce-style="-ms-interpolation-mode: bicubic; border: 0; height: auto; line-height: 100%; outline: none; text-decoration: none;"></td>
                                                    </tr>
                                                </tbody>
                                            </table>
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td align="center" class="content_cell bg_white brounded bt_primary px py_md" style="font-size: 0px; text-align: center; border-bottom: 1px solid rgb(218, 218, 218); background-color: rgb(255, 255, 255); border-top: 1px solid rgb(226, 234, 240); border-radius: 4px; text-size-adjust: 100%; border-collapse: collapse;" data-mce-style="font-size: 0; text-align: center; border-bottom: 1px solid #dadada; background-color: #ffffff; border-top: 1px solid #e2eaf0; border-radius: 4px; -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt; ">
                                        <div style="background:#f7f7f7;" data-mce-style="background:#f7f7f7;">
                                            <table class="content_column mce-item-table" align="center" border="0" width="100%" cellspacing="0" cellpadding="0" style="text-align: center; text-size-adjust: 100%; border-spacing: 0px; border-collapse: collapse;" data-mce-style="text-align: center;-webkit-text-size-adjust: 100%;-ms-text-size-adjust: 100%;mso-table-lspace: 0pt;mso-table-rspace: 0pt;">
                                                <tbody>
                                                    <tr>
                                                        <td class="column_cell" style="background: rgb(247, 247, 247); vertical-align: top; color: rgb(51, 51, 51); padding: 20px 0px 0px; text-size-adjust: 100%; border-collapse: collapse;" data-mce-style="background:rgb(247, 247, 247);vertical-align: top;color: #333333;padding-top: 20px;padding-bottom:0;padding-left: 0;padding-right: 0;-webkit-text-size-adjust: 100%;-ms-text-size-adjust: 100%;mso-table-lspace: 0pt;mso-table-rspace: 0pt;">
                                                            <table align="center" border="0" cellspacing="0" width="100%" cellpadding="0" style="text-size-adjust: 100%; margin: 0px auto; padding-bottom: 10px; border-spacing: 0px; border-collapse: collapse;" data-mce-style="-webkit-text-size-adjust: 100%;-ms-text-size-adjust: 100%;mso-table-lspace: 0pt;mso-table-rspace: 0pt;margin: 0 auto;padding-bottom:10px;" class="mce-item-table">
                                                                <tbody>
                                                                    <tr>
                                                                        <td class="column_cell md_py" style="font-size: 16px; font-family: Arial, Helvetica, sans-serif; min-width: 192px; padding: 13px 20px; border-radius: 2px; line-height: normal; text-align: center; font-weight: bold; border-collapse: collapse; text-size-adjust: 100%;" data-mce-style="font-size: 16px;font-family: Arial, Helvetica, sans-serif;min-width:192px;padding: 13px 20px;border-radius: 2px;line-height: normal;text-align: center;font-weight: bold;">
                                                                            <h2 style="color: #333333;" data-mce-style="color: #333333;"><?= $model['mcm_RegistrationNo'] ?>&nbsp;- New Supplier Registration</h2>
                                                                            <p class="text_lead text_secondary mb_md" style="color: rgb(51, 51, 51); font-family: Arial, Helvetica, sans-serif; margin-top: 0px; margin-bottom: 10px; word-break: break-word; font-size: 16px; text-align: left; text-size-adjust: 100%;" data-mce-style="color: #333333; font-family: Arial, Helvetica, sans-serif; margin-top: 0px; margin-bottom: 10px; word-break: break-word; font-size: 16px; text-align: left;">Dear Team,</p>
                                                                        </td>
                                                                    </tr>
                                                                </tbody>
                                                            </table>
                                                        </td>
                                                    </tr>
                                                </tbody>
                                            </table>
                                        </div>
                                        <div class="column_row" style="font-size: 0; text-align: center;  margin: 0 auto;" data-mce-style="font-size: 0; text-align: center;  margin: 0 auto;">
                                            <div class="col_3" style="vertical-align: top; display: inline-block; width: 100%; " data-mce-style="vertical-align: top; display: inline-block; width: 100%;">
                                                <br>
                                            </div>
                                        </div>
                                        <div class="colunm_row md" style="max-width: 100%" data-mce-style="max-width: 100%">
                                            <table class="content_column md_mx mce-item-table" align="center" border="0" cellspacing="0" cellpadding="0" width="100%" style="text-align: center; text-size-adjust: 100%; border-spacing: 0px; border-collapse: collapse;" data-mce-style="text-align: center;-webkit-text-size-adjust: 100%;-ms-text-size-adjust: 100%;mso-table-lspace: 0pt;mso-table-rspace: 0pt;">
                                                <tbody>
                                                    <tr>
                                                        <td class="column_cell md_px" style="text-size-adjust: 100%; padding: 20px; border-collapse: collapse;" data-mce-style="-webkit-text-size-adjust: 100%;-ms-text-size-adjust: 100%;mso-table-lspace: 0pt;mso-table-rspace: 0pt;padding: 20px 20px;">
                                                            
                                                            <table class="content_column md_mx mce-item-table" align="center" border="0" cellspacing="0" cellpadding="0" width="100%" style="text-align: center; text-size-adjust: 100%; border-spacing: 0px; border-collapse: collapse;" data-mce-style="text-align: center;-webkit-text-size-adjust: 100%;-ms-text-size-adjust: 100%;mso-table-lspace: 0pt;mso-table-rspace: 0pt;">
                                                                <tbody>
                                                                    <tr>
                                                                        <td class="column_cell md_px" style="text-size-adjust: 100%; padding: 0px; border-collapse: collapse;" data-mce-style="-webkit-text-size-adjust: 100%;-ms-text-size-adjust: 100%;mso-table-lspace: 0pt;mso-table-rspace: 0pt;padding:0px;">
                                                                            <p class="text_lead text_secondary mb_md" style="margin-top: 0px; margin-bottom: 10px; word-break: break-word; text-align: left; text-size-adjust: 100%;" data-mce-style="color: #333333; font-family: Arial, Helvetica, sans-serif; margin-top: 0px; margin-bottom: 10px; word-break: break-word; font-size: 16px; text-align: left;"><span style="color: #333333; font-family: Arial, Helvetica, sans-serif;" data-mce-style="color: #333333; font-family: Arial, Helvetica, sans-serif;"><span style="font-size: 16px;" data-mce-style="font-size: 16px;">The following Supplier has registered on RABT, but is yet to complete the payment.&nbsp;</span></span>
                                                                            </p>
                                                                            <p class="text_lead text_secondary mb_md" style="margin-top: 0px; margin-bottom: 10px; word-break: break-word; text-align: left; text-size-adjust: 100%;" data-mce-style="color: #333333; font-family: Arial, Helvetica, sans-serif; margin-top: 0px; margin-bottom: 10px; word-break: break-word; font-size: 16px; text-align: left;"><span style="color: #333333; font-family: Arial, Helvetica, sans-serif;" data-mce-style="color: #333333; font-family: Arial, Helvetica, sans-serif;"><span style="font-size: 16px;" data-mce-style="font-size: 16px;">Please find the Proforma Invoice attached to this email for reference. &nbsp;</span></span>
                                                                            </p>
                                                                            <p class="text_lead text_secondary mb_md" style="margin-top: 0px; margin-bottom: 10px; word-break: break-word; text-align: left; text-size-adjust: 100%;" data-mce-style="color: #333333; font-family: Arial, Helvetica, sans-serif; margin-top: 0px; margin-bottom: 10px; word-break: break-word; font-size: 16px; text-align: left;"><span style="color: #333333; font-family: Arial, Helvetica, sans-serif;" data-mce-style="color: #333333; font-family: Arial, Helvetica, sans-serif;"><span style="font-size: 16px;" data-mce-style="font-size: 16px;"><strong>RABT Registration Number:&nbsp; </strong> <?= $model['mcm_RegistrationNo'] ?></span></span>
                                                                            </p>
                                                                            <p class="text_lead text_secondary mb_md" style="margin-top: 0px; margin-bottom: 15px; word-break: break-word; text-align: center; text-size-adjust: 100%;" data-mce-style="margin-top: 0px; margin-bottom: 15px; word-break: break-word; text-align: center;"><strong><span style="text-decoration: underline;" data-mce-style="text-decoration: underline;"><span style="color: #333333; font-family: Arial, Helvetica, sans-serif;" data-mce-style="color: #333333; font-family: Arial, Helvetica, sans-serif;"><span style="font-size: 16px;font-weight: bold;" data-mce-style="font-size: 16px;font-weight: bold;">Company Details</span></span></span></strong></p>
                                                                            <p class="text_lead text_secondary mb_md" style="margin-top: 0px; margin-bottom: 10px; word-break: break-word; text-align: left; text-size-adjust: 100%;" data-mce-style="margin-top: 0px; margin-bottom: 10px; word-break: break-word; text-align: left;"><span style="color: #333333; font-family: Arial, Helvetica, sans-serif;" data-mce-style="color: #333333; font-family: Arial, Helvetica, sans-serif;"><span style="font-size: 16px;" data-mce-style="font-size: 16px;"><strong>Company: </strong> <?= $model['MCM_CompanyName'] ?></span></span>
                                                                            </p>
                                                                            <p class="text_lead text_secondary mb_md" style="margin-top: 0px; margin-bottom: 10px; word-break: break-word; text-align: left; text-size-adjust: 100%;" data-mce-style="margin-top: 0px; margin-bottom: 10px; word-break: break-word; text-align: left;"><span style="color: #333333; font-family: Arial, Helvetica, sans-serif;" data-mce-style="color: #333333; font-family: Arial, Helvetica, sans-serif;"><span style="font-size: 16px;" data-mce-style="font-size: 16px;"><strong>Country: </strong> <?= $model['CyM_CountryName_en'] ?></span></span>
                                                                            </p>
                                                                            <p class="text_lead text_secondary mb_md" style="margin-top: 0px; margin-bottom: 10px; word-break: break-word; text-align: left; text-size-adjust: 100%;" data-mce-style="margin-top: 0px; margin-bottom: 10px; word-break: break-word; text-align: left;"><span style="color: #333333; font-family: Arial, Helvetica, sans-serif;" data-mce-style="color: #333333; font-family: Arial, Helvetica, sans-serif;"><span style="font-size: 16px;" data-mce-style="font-size: 16px;"><strong>Classification: </strong> <?= $model['ClM_ClassificationType'] ?></span></span>
                                                                            </p>
                                                                            <p class="col_s" style="margin-top: 0px; margin-bottom: 10px; word-break: break-word; text-align: left; text-size-adjust: 100%;" data-mce-style="margin-top: 0px; margin-bottom: 10px; word-break: break-word; text-align: left;"><span style="color: #333333; font-family: Arial, Helvetica, sans-serif;" data-mce-style="color: #333333; font-family: Arial, Helvetica, sans-serif;"><span style="color:#333333 ; font-size: 16px;" data-mce-style="color:#333333; font-size: 16px;"><strong>Email:</strong><span style="color:#333333;text-decoration: none;" data-mce-style="color:#333333;text-decoration: none;"> <?= $model['UM_EmailID'] ?></span></span>
                                                                            </span>
                                                                            </p>
                                                                            
                                                                            <p class="text_lead text_secondary mb_md" style="margin-top: 0px; margin-bottom: 10px; word-break: break-word; text-align: left; text-size-adjust: 100%;" data-mce-style="margin-top: 0px; margin-bottom: 10px; word-break: break-word; text-align: left;">
                                                                                <br>
                                                                            </p>
                                                                            <p class="text_lead text_secondary mb_md" style="margin-top:0;margin-bottom:15px;word-break:break-word;text-align:center;text-size-adjust:100%" data-mce-style="margin-top: 0px; margin-bottom: 15px; word-break: break-word; text-align: center;"><strong><span style="text-decoration:underline" data-mce-style="text-decoration: underline;"><span style="text-align:center" data-mce-style="text-align: center;"><span style="color:#333;font-family:Arial,Helvetica,sans-serif" data-mce-style="color: #333333; font-family: Arial, Helvetica, sans-serif;"><span style="font-size:16px;font-weight: bold;" data-mce-style="font-size: 16px;font-weight: bold;">Payment Contact</span></span></span></span></strong></p>
                                                                            <p class="text_lead text_secondary mb_md" style="margin-top:0;margin-bottom:10px;word-break:break-word;text-align:left;text-size-adjust:100%" data-mce-style="margin-top: 0px; margin-bottom: 10px; word-break: break-word; text-align: left;"><strong><span style="text-align:center" data-mce-style="text-align: center;"><span style="color:#333;font-family:Arial,Helvetica,sans-serif" data-mce-style="color: #333333; font-family: Arial, Helvetica, sans-serif;"><span style="font-size:16px" data-mce-style="font-size: 16px;">Contact Person: </span></span></span></strong><span style="text-align:center" data-mce-style="text-align: center;"><span style="color:#333;font-family:Arial,Helvetica,sans-serif" data-mce-style="color: #333333; font-family: Arial, Helvetica, sans-serif;"><span style="font-size:16px" data-mce-style="font-size: 16px;"> Ratchana S</span></span>
                                                                                </span>
                                                                            </p>
                                                                            <p class="text_lead text_secondary mb_md" style="margin-top:0;margin-bottom:10px;word-break:break-word;text-align:left;text-size-adjust:100%" data-mce-style="margin-top: 0px; margin-bottom: 10px; word-break: break-word; text-align: left;"><strong><span style="text-align:center" data-mce-style="text-align: center;"><span style="color:#333;font-family:Arial,Helvetica,sans-serif" data-mce-style="color: #333333; font-family: Arial, Helvetica, sans-serif;"><span style="font-size:16px" data-mce-style="font-size: 16px;">Department: </span></span></span></strong><span style="text-align:center" data-mce-style="text-align: center;"><span style="color:#333;font-family:Arial,Helvetica,sans-serif" data-mce-style="color: #333333; font-family: Arial, Helvetica, sans-serif;"><span style="font-size:16px" data-mce-style="font-size: 16px;"> </span></span>
                                                                            </span>
                                                                            </p>
                                                                            <p class="text_lead text_secondary mb_md" style="margin-top:0;margin-bottom:10px;word-break:break-word;text-align:left;text-size-adjust:100%" data-mce-style="margin-top: 0px; margin-bottom: 10px; word-break: break-word; text-align: left;"><strong><span style="text-align:center" data-mce-style="text-align: center;"><span style="color:#333;font-family:Arial,Helvetica,sans-serif" data-mce-style="color: #333333; font-family: Arial, Helvetica, sans-serif;"><span style="font-size:16px" data-mce-style="font-size: 16px;">Designation: </span></span></span></strong><span style="text-align:center" data-mce-style="text-align: center;"><span style="color:#333;font-family:Arial,Helvetica,sans-serif" data-mce-style="color: #333333; font-family: Arial, Helvetica, sans-serif;"><span style="font-size:16px" data-mce-style="font-size: 16px;"> Designation</span></span>
                                                                                </span>
                                                                            </p>
                                                                            <p class="text_lead text_secondary mb_md" style="margin-top:0;margin-bottom:10px;word-break:break-word;text-align:left;text-size-adjust:100%" data-mce-style="margin-top: 0px; margin-bottom: 10px; word-break: break-word; text-align: left;"><strong><span style="text-align:center" data-mce-style="text-align: center;"><span style="color:#333;font-family:Arial,Helvetica,sans-serif" data-mce-style="color: #333333; font-family: Arial, Helvetica, sans-serif;"><span style="font-size:16px" data-mce-style="font-size: 16px;">Email: </span></span></span></strong><span style="text-align:center" data-mce-style="text-align: center;"><span style="color:#006cb7;font-family:Arial,Helvetica,sans-serif" data-mce-style="color: #006cb7; font-family: Arial, Helvetica, sans-serif;"><span style="font-size:16px;color: #333333;" data-mce-style="font-size: 16px;color:#333333;"> ratchu@ymail.com</span></span>
                                                                                </span>
                                                                            </p>
                                                                            <p class="text_lead text_secondary mb_md" style="margin-top:0;margin-bottom:10px;word-break:break-word;text-align:left;text-size-adjust:100%" data-mce-style="margin-top: 0px; margin-bottom: 10px; word-break: break-word; text-align: left;"><strong><span style="text-align:center" data-mce-style="text-align: center;"><span style="color:#333;font-family:Arial,Helvetica,sans-serif" data-mce-style="color: #333333; font-family: Arial, Helvetica, sans-serif;"><span style="font-size:16px" data-mce-style="font-size: 16px;">Mobile: </span></span></span></strong><span style="text-align:center" data-mce-style="text-align: center;"><span style="color:#333;font-family:Arial,Helvetica,sans-serif" data-mce-style="color: #333333; font-family: Arial, Helvetica, sans-serif;"><span style="font-size:16px" data-mce-style="font-size: 16px;"> +968 14523666</span></span>
                                                                                </span>
                                                                            </p>
                                                                            <p class="text_lead text_secondary mb_md" style="color:#333;margin-top:0;margin-bottom:10px;word-break:break-word;text-align:left;text-size-adjust:100%" data-mce-style="color: #333333; font-family: Arial, Helvetica, sans-serif; margin-top: 0px; margin-bottom: 10px; word-break: break-word; font-size: 16px; text-align: left;">
                                                                                <br>
                                                                            </p>
                                                                            <p class="text_lead text_secondary mb_md" style="margin-top:0;margin-bottom:15px;word-break:break-word;text-align:center;text-size-adjust:100%" data-mce-style="margin-top: 0px; margin-bottom: 15px; word-break: break-word; text-align: center;"><strong><span style="text-decoration:underline" data-mce-style="text-decoration: underline;"><span style="text-align:center" data-mce-style="text-align: center;"><span style="color:#333;font-family:Arial,Helvetica,sans-serif" data-mce-style="color: #333333; font-family: Arial, Helvetica, sans-serif;"><span style="font-size:16px;font-weight: bold;" data-mce-style="font-size: 16px;font-weight: bold;">RABT Supply Chain Certification Fee Details</span></span></span></span></strong></p>
                                                                            <p class="text_lead text_secondary mb_md" style="margin-top:0;margin-bottom:10px;word-break:break-word;text-align:left;text-size-adjust:100%" data-mce-style="margin-top: 0px; margin-bottom: 10px; word-break: break-word; text-align: left;"><strong><span style="text-align:center" data-mce-style="text-align: center;"><span style="color:#333;font-family:Arial,Helvetica,sans-serif" data-mce-style="color: #333333; font-family: Arial, Helvetica, sans-serif;"><span style="font-size:16px" data-mce-style="font-size: 16px;">Products &amp; Services Pack: </span></span></span></strong><span style="text-align:center" data-mce-style="text-align: center;"><span style="color:#333;font-family:Arial,Helvetica,sans-serif" data-mce-style="color: #333333; font-family: Arial, Helvetica, sans-serif;"><span style="font-size:16px" data-mce-style="font-size: 16px;"> SME-Micro</span></span>
                                                                                </span>
                                                                            </p>
                                                                            <p class="text_lead text_secondary mb_md" style="margin-top:0;margin-bottom:10px;word-break:break-word;text-align:left;text-size-adjust:100%" data-mce-style="margin-top: 0px; margin-bottom: 10px; word-break: break-word; text-align: left;"><strong><span style="text-align:center" data-mce-style="text-align: center;"><span style="color:#333;font-family:Arial,Helvetica,sans-serif" data-mce-style="color: #333333; font-family: Arial, Helvetica, sans-serif;"><span style="font-size:16px" data-mce-style="font-size: 16px;">Certification Validity:&nbsp; </span></span></span></strong><span style="text-align:center" data-mce-style="text-align: center;"><span style="color:#333;font-family:Arial,Helvetica,sans-serif" data-mce-style="color: #333333; font-family: Arial, Helvetica, sans-serif;"><span style="font-size:16px" data-mce-style="font-size: 16px;">   </span></span>
                                                                            </span>
                                                                            </p>
                                                                            <p class="text_lead text_secondary mb_md" style="margin-top:0;margin-bottom:10px;word-break:break-word;text-align:left;text-size-adjust:100%" data-mce-style="margin-top: 0px; margin-bottom: 10px; word-break: break-word; text-align: left;"><strong><span style="text-align:center" data-mce-style="text-align: center;"><span style="color:#333;font-family:Arial,Helvetica,sans-serif" data-mce-style="color: #333333; font-family: Arial, Helvetica, sans-serif;"><span style="font-size:16px" data-mce-style="font-size: 16px;">Certification Fee: </span></span></span></strong><span style="text-align:center" data-mce-style="text-align: center;"><span style="color:#333;font-family:Arial,Helvetica,sans-serif" data-mce-style="color: #333333; font-family: Arial, Helvetica, sans-serif;"><span style="font-size:16px" data-mce-style="font-size: 16px;"> <?= $model['msm_baseprice'] ?> </span></span>
                                                                                </span>
                                                                            </p>
                                                                            <p class="text_lead text_secondary mb_md" style="margin-top:0;margin-bottom:10px;word-break:break-word;text-align:left;text-size-adjust:100%" data-mce-style="margin-top: 0px; margin-bottom: 10px; word-break: break-word; text-align: left;"><strong><span style="text-align:center" data-mce-style="text-align: center;"><span style="color:#333;font-family:Arial,Helvetica,sans-serif" data-mce-style="color: #333333; font-family: Arial, Helvetica, sans-serif;"><span style="font-size:16px" data-mce-style="font-size: 16px;">Discount (): </span></span></span></strong><span style="text-align:center" data-mce-style="text-align: center;"><span style="color:#006cb7;font-family:Arial,Helvetica,sans-serif" data-mce-style="color: #006cb7; font-family: Arial, Helvetica, sans-serif;"><span style="font-size:16px;color: #333333;" data-mce-style="font-size: 16px;color:#333333;"> <?= $model['msm_duration']/365 ?></span></span>
                                                                                </span>
                                                                            </p>
                                                                            <p class="text_lead text_secondary mb_md" style="margin-top:0;margin-bottom:10px;word-break:break-word;text-align:left;text-size-adjust:100%" data-mce-style="margin-top: 0px; margin-bottom: 10px; word-break: break-word; text-align: left;"><strong><span style="text-align:center" data-mce-style="text-align: center;"><span style="color:#333;font-family:Arial,Helvetica,sans-serif" data-mce-style="color: #333333; font-family: Arial, Helvetica, sans-serif;"><span style="font-size:16px" data-mce-style="font-size: 16px;">Promo Code Applied (Discount): </span></span></span></strong><span style="text-align:center" data-mce-style="text-align: center;"><span style="color:#333;font-family:Arial,Helvetica,sans-serif" data-mce-style="color: #333333; font-family: Arial, Helvetica, sans-serif;"><span style="font-size:16px" data-mce-style="font-size: 16px;"> </span></span>
                                                                                </span>
                                                                            </p>
                                                                            <p class="text_lead text_secondary mb_md" style="margin-top:0;margin-bottom:10px;word-break:break-word;text-align:left;text-size-adjust:100%" data-mce-style="margin-top: 0px; margin-bottom: 10px; word-break: break-word; text-align: left;"><strong><span style="text-align:center" data-mce-style="text-align: center;"><span style="color:#333;font-family:Arial,Helvetica,sans-serif" data-mce-style="color: #333333; font-family: Arial, Helvetica, sans-serif;"><span style="font-size:16px" data-mce-style="font-size: 16px;">VAT Charges (5%): </span></span></span></strong><span style="text-align:center" data-mce-style="text-align: center;"><span style="color:#006cb7;font-family:Arial,Helvetica,sans-serif" data-mce-style="color: #006cb7; font-family: Arial, Helvetica, sans-serif;"><span style="font-size:16px;color: #333333;" data-mce-style="font-size: 16px;color:#333333;"> </span></span>
                                                                            </span>
                                                                            </p>
                                                                            <p class="text_lead text_secondary mb_md" style="margin-top:0;margin-bottom:10px;word-break:break-word;text-align:left;text-size-adjust:100%" data-mce-style="margin-top: 0px; margin-bottom: 10px; word-break: break-word; text-align: left;"><strong><span style="text-align:center" data-mce-style="text-align: center;"><span style="color:#333;font-family:Arial,Helvetica,sans-serif" data-mce-style="color: #333333; font-family: Arial, Helvetica, sans-serif;"><span style="font-size:16px" data-mce-style="font-size: 16px;">Total Amount to be Paid: </span></span></span></strong><span style="text-align:center" data-mce-style="text-align: center;"><span style="color:#006cb7;font-family:Arial,Helvetica,sans-serif" data-mce-style="color: #006cb7; font-family: Arial, Helvetica, sans-serif;"><span style="font-size:16px;color: #333333;" data-mce-style="font-size: 16px;color:#333333;"> </span></span>
                                                                            </span>
                                                                             </p>
                                                                        <p class="text_lead text_secondary mb_md" style="color: rgb(51, 51, 51); font-family: cairo; margin-top: 0px; margin-bottom: 0px; word-break: break-word; font-size: 16px; text-size-adjust: 100%;" data-mce-style="color: #333; font-family: cairo; margin-top: 0px; margin-bottom: 0px; word-break: break-word; font-size: 16px;">
                                                                            <br>
                                                                        </p>
                                                                       
                                                                        <table role="presentation" class="ebutton mce-item-table" align="center" border="0" cellspacing="0" cellpadding="0" style="color: rgb(51, 51, 51); text-size-adjust: 100%; margin: 0px auto; border-spacing: 0px; border-collapse: collapse;" data-mce-style="-webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt; margin: 0px auto;">
                                                                            <tbody>
                                                                                <tr>
                                                                                    <td class="column_cell" style="font-family: cairo; color: rgb(255, 255, 255); background-color: rgb(76, 160, 171); text-size-adjust: 100%; font-size: 16px; padding: 10px 24px; border-radius: 2px; line-height: normal; text-align: center; font-weight: bold; border-collapse: collapse;" data-mce-style="color:#fff !important; background-color: #4ca0ab; -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt; text-size-adjust: 100%; font-size: 16px; padding: 10px 24px; border-radius: 2px; line-height: normal; text-align: center; font-weight: bold;"><a class="column_cell" data-mce-href="http://192.168.1.53/rabt/app/admin/login" href="http://192.168.1.53/rabt/app/admin/login" target="_blank" rel="noopener" style="cursor: pointer; color: rgb(255, 255, 255); text-decoration: none; font-weight: bold; overflow-wrap: break-word; text-size-adjust: 100%;" data-mce-style="color: #ffffff;text-decoration: none;font-weight: bold;cursor:pointer;"><span class="column_cell">View Details</span></a></td>
                                                                                </tr>
                                                                            </tbody>
                                                                        </table>
                                                                        <p class="text_lead text_secondary mb_md" style="color: rgb(51, 51, 51); font-family: cairo; margin-top: 0px; margin-bottom: 0px; word-break: break-word; font-size: 16px; text-size-adjust: 100%;" data-mce-style="color: #333; font-family: cairo; margin-top: 0px; margin-bottom: 0px; word-break: break-word; font-size: 16px;">
                                                                            <br>
                                                                        </p>
                                                                           
                                                                        </td>
                                                                    </tr>
                                                                </tbody>
                                                            </table>
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td align="center" class="content_cell" style="background-color: rgb(249, 249, 249); font-size: 0px; text-align: center; text-size-adjust: 100%; border-collapse: collapse;" data-mce-style="background-color: #f9f9f9; font-size: 0; text-align: center; -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt;">
                                                            <div class="column_row" style="font-size: 0; text-align: center; max-width: 100%; margin: 0 auto;" data-mce-style="font-size: 0; text-align: center; max-width: 100%px; margin: 0 auto;">
                                                                <table class="column mce-item-table" role="presentation" align="center" width="100%" cellspacing="0" cellpadding="0" border="0" style="margin-top: 20px; vertical-align: top; text-size-adjust: 100%; border-spacing: 0px; border-collapse: collapse;" data-mce-style="margin-top: 20px;vertical-align: top; -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt;">
                                                                    <tbody>
                                                                        <tr>
                                                                            <td class="column_cell px py_xs text_primary text_left mobile_center" style="margin-left: 20px; vertical-align: top; color: rgb(35, 118, 220); text-align: left; text-size-adjust: 100%; float: left; width: 40%; padding: 20px; border-collapse: collapse;" data-mce-style="margin-left: 20px; vertical-align: top; color: #2376dc; text-align: left; -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt; float: left; width: 40%; padding: 20px 20px;">
                                                                                <img src="http://192.168.1.53/rabt/backend/assets/images/mail/img/newrabtfootlogo.png" alt="rabtlogo" style="-ms-interpolation-mode: bicubic; border: 0; height: auto; line-height: 100%; outline: none; text-decoration: none;" data-mce-src="http://192.168.1.53/rabt/backend/assets/images/mail/img/newrabtfootlogo.png" data-mce-style="-ms-interpolation-mode: bicubic; border: 0; height: auto; line-height: 100%; outline: none; text-decoration: none;">
                                                                        </td>
                                                                            <td class="column_cell px py_xs text_right mobile_center" style="vertical-align: top; text-align: left; text-size-adjust: 100%; float: right; width: 45%; padding: 20px 10px; border-collapse: collapse;" data-mce-style="padding-right: 10px;vertical-align: top; text-align: left; -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt; float: right; width: 47%; padding: 20px 10px;">
                                                                                <p class="text_link text_xs" style="color: rgb(51, 51, 51); font-family: cairo; margin-top: 0px; margin-bottom: 5px; word-break: break-word; font-size: 16px; line-height: 13px; text-size-adjust: 100%;" data-mce-style="color: #333; font-family: cairo; margin-top: 0px; margin-bottom: 5px; word-break: break-word; font-size: 16px; line-height: 13px;"><span style="color: #333; text-decoration: none;font-weight:bold; " data-mce-style="color: #333; text-decoration: none;font-weight:bold;">Address Info</span></p>

                                                                                <p class="text_link text_xs" style="color: rgb(51, 51, 51); font-family: cairo; margin-top: 0px; margin-bottom: 5px; word-break: break-word; font-size: 14px; line-height: 20px; text-size-adjust: 100%;" data-mce-style="color: #333; font-family: cairo; margin-top: 0px; margin-bottom: 5px; word-break: break-word; font-size: 14px line-height: 20px;"><span style="color: #333; text-decoration: none;" data-mce-style="color: #333; text-decoration: none;">Business Gateways International LLC<br>Knowledge Oasis Muscat(KOM), 
                                                                                    <br> Rusayl, Sultanate of Oman. </span></p>
                                                                            </td>
                                                                        </tr>
                                                                    </tbody>
                                                                </table>
                                                                <table class="column mce-item-table" role="presentation" align="center" width="100%" cellspacing="0" cellpadding="0" border="0" style="vertical-align: top; text-size-adjust: 100%; border-spacing: 0px; border-collapse: collapse;" data-mce-style="padding: 20px 10px;vertical-align: top; -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt;">

                                                                    <tbody>
                                                                        <tr>
                                                                            <td align="center" width="100%" style="width: 100%; max-width: 100%; text-align: center; padding-bottom: 10px; border-collapse: collapse; text-size-adjust: 100%;" data-mce-style="width: 100%;max-width: 100%;text-align:center; padding-bottom: 10px;">
                                                                                <p style="font-family: cairo; font-style: normal; word-break: break-word; line-height: 20px; margin-bottom: 10px; text-align: center; text-size-adjust: 100%;" data-mce-style="font-family: cairo;font-style: normal;color: #333333; font-family: cairo; word-break: break-word; font-size: 16px; line-height: 20px; margin-bottom: 10px; text-align: center;font-style: normal;font-size: 15px;">
                                                                                    <span style="font-family: cairo;font-style: normal;font-size: 14px; color: #333333; font-family: cairo;" data-mce-style="font-family: cairo;font-style: normal;font-size: 14px; color: #333333; font-family: cairo;">
                                                                                        The Digital Platform for Oman’s Industrial Sector
                                                                                </span>
                                                                                </p>
                                                                                <p class="img_inline mb" style="color: inherit; font-family: cairo; margin-top: 0px; margin-bottom: 16px; word-break: break-word; font-size: 16px; line-height: 100%; clear: both; text-size-adjust: 100%;" data-mce-style="color: inherit; font-family: cairo; margin-top: 0px; margin-bottom: 16px; word-break: break-word; font-size: 16px; line-height: 100%; clear: both;">
                                                                                    <a href="#" style="text-size-adjust: 100%; text-decoration: none; color: rgb(149, 155, 160); font-family: cairo; margin-top: 0px; margin-bottom: 0px; word-break: break-word; overflow-wrap: break-word;" data-mce-href="#" data-mce-style="-webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; text-decoration: none; color: #959ba0; font-family: cairo; margin-top: 0px; margin-bottom: 0px; word-break: break-word;"><img src="http://192.168.1.53/rabt/backend/assets/images/mail/img/whatsapp.png" width="24" height="24" alt="whatsapp" style="max-width: 24px; -ms-interpolation-mode: bicubic; border: 0; height: auto; line-height: 100%; outline: none; text-decoration: none;" data-mce-src="http://192.168.1.53/rabt/backend/assets/images/mail/img/whatsapp.png" data-mce-style="max-width: 24px; -ms-interpolation-mode: bicubic; border: 0; height: auto; line-height: 100%; outline: none; text-decoration: none;"></a>&nbsp;
                                                                                    <a href="#" style="text-size-adjust: 100%; text-decoration: none; color: rgb(149, 155, 160); font-family: cairo; margin-top: 0px; margin-bottom: 0px; word-break: break-word; overflow-wrap: break-word;" data-mce-href="#" data-mce-style="-webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; text-decoration: none; color: #959ba0; font-family: cairo; margin-top: 0px; margin-bottom: 0px; word-break: break-word;"><img src="http://192.168.1.53/rabt/backend/assets/images/mail/img/facebook.png" width="24" height="24" alt="facebook" style="max-width: 24px; -ms-interpolation-mode: bicubic; border: 0; height: auto; line-height: 100%; outline: none; text-decoration: none;" data-mce-src="http://192.168.1.53/rabt/backend/assets/images/mail/img/facebook.png" data-mce-style="max-width: 24px; -ms-interpolation-mode: bicubic; border: 0; height: auto; line-height: 100%; outline: none; text-decoration: none;"></a>&nbsp; 
                                                                                    <a href="#" style="text-size-adjust: 100%; text-decoration: none; color: rgb(149, 155, 160); font-family: cairo; margin-top: 0px; margin-bottom: 0px; word-break: break-word; overflow-wrap: break-word;" data-mce-href="#" data-mce-style="-webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; text-decoration: none; color: #959ba0; font-family: cairo; margin-top: 0px; margin-bottom: 0px; word-break: break-word;"><img src="http://192.168.1.53/rabt/backend/assets/images/mail/img/twitter.png" width="24" height="24" alt="Youtube" style="max-width: 24px; -ms-interpolation-mode: bicubic; border: 0; height: auto; line-height: 100%; outline: none; text-decoration: none;" data-mce-src="http://192.168.1.53/rabt/backend/assets/images/mail/img/twitter.png" data-mce-style="max-width: 24px; -ms-interpolation-mode: bicubic; border: 0; height: auto; line-height: 100%; outline: none; text-decoration: none;"></a>&nbsp; 
                                                                                    <a href="#" style="text-size-adjust: 100%; text-decoration: none; color: rgb(149, 155, 160); font-family: cairo; margin-top: 0px; margin-bottom: 0px; word-break: break-word; overflow-wrap: break-word;" data-mce-href="#" data-mce-style="-webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; text-decoration: none; color: #959ba0; font-family: cairo; margin-top: 0px; margin-bottom: 0px; word-break: break-word;"><img src="http://192.168.1.53/rabt/backend/assets/images/mail/img/youtube.png" width="24" height="24" alt="linkedin" style="max-width: 24px; -ms-interpolation-mode: bicubic; border: 0; height: auto; line-height: 100%; outline: none; text-decoration: none;" data-mce-src="http://192.168.1.53/rabt/backend/assets/images/mail/img/youtube.png" data-mce-style="max-width: 24px; -ms-interpolation-mode: bicubic; border: 0; height: auto; line-height: 100%; outline: none; text-decoration: none;"></a>&nbsp;
                                                                                    <a href="#" style="text-size-adjust: 100%; text-decoration: none; color: rgb(149, 155, 160); font-family: cairo; margin-top: 0px; margin-bottom: 0px; word-break: break-word; overflow-wrap: break-word;" data-mce-href="#" data-mce-style="-webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; text-decoration: none; color: #959ba0; font-family: cairo; margin-top: 0px; margin-bottom: 0px; word-break: break-word;"><img src="http://192.168.1.53/rabt/backend/assets/images/mail/img/linkdin.png" width="24" height="24" alt="twitter" style="max-width: 24px; -ms-interpolation-mode: bicubic; border: 0; height: auto; line-height: 100%; outline: none; text-decoration: none;" data-mce-src="http://192.168.1.53/rabt/backend/assets/images/mail/img/linkdin.png" data-mce-style="max-width: 24px; -ms-interpolation-mode: bicubic; border: 0; height: auto; line-height: 100%; outline: none; text-decoration: none;"></a>&nbsp;
                                                                                </p>
                                                                            </td>
                                                                        </tr>
                                                                    </tbody>
                                                                </table>
                                                                <table class="content_section mce-item-table" role="presentation" align="center" width="100%" cellspacing="0" cellpadding="0" border="0" style="padding: 15px 0px; margin-left: auto; margin-right: auto; background-color: rgb(230, 230, 230); text-size-adjust: 100%; border-spacing: 0px; border-collapse: collapse;" data-mce-style="padding: 15px 0;margin-left: auto; margin-right: auto; background-color: #e6e6e6;-webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt;">
                                                                    <tbody>
                                                                        <tr>
                                                                            <td class="column_cell px py_xs text_right mobile_center" style="vertical-align: top; text-align: left; text-size-adjust: 100%; float: left; width: 57%; padding: 15px 0px 15px 10px; border-collapse: collapse;" data-mce-style="vertical-align: top; text-align: left; -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt; float: left; width: 57%; padding: 15px 0 15px 10px;">
                                                                                <p class="mb_xs" style="margin-top: 15px; color: rgb(51, 51, 51); font-family: cairo; margin-bottom: 0px; word-break: break-word; font-size: 13px; line-height: 26px; text-size-adjust: 100%;" data-mce-style="margin-top: 15px;color: #333; font-family: cairo; margin-bottom: 0px; word-break: break-word; font-size: 13px; line-height: 26px;">© 2022 Industrial Innovation Academy. All Rights Reserved</p>
                                                                            </td>
                                                                            <td class="column_cell px py_xs text_right mobile_center" style="vertical-align: top; text-align: left; text-size-adjust: 100%; float: left; width: 12%; padding: 14px 0px; border-collapse: collapse;" data-mce-style="vertical-align: top; text-align: left; -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt; float: left; width: 12%; padding: 15px 0;">
                                                                                <p class="mb_xs" style="margin-top: 15px; color: rgb(51, 51, 51); font-family: cairo; margin-bottom: 0px; word-break: break-word; font-size: 13px; line-height: 26px; margin-left: 13px; text-size-adjust: 100%;" data-mce-style="margin-top: 14px;color: #333; font-family: cairo; margin-bottom: 0px; word-break: break-word; font-size: 13px; line-height: 26px;margin-left: 13px;">Driven by</p>
                                                                            </td>
                                                                            <td class="column_cell px py_xs text_primary text_left mobile_center" style="vertical-align: top; color: rgb(51, 51, 51); text-align: right; text-size-adjust: 100%; float: right; width: 27%; padding: 15px 10px 15px 0px; border-collapse: collapse;" data-mce-style="vertical-align: top; color: #333; text-align: right; -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt; float: right; width: 27%; padding:15px 10px 15px 0;">
                                                                            <p style="margin: 0px; text-size-adjust: 100%;"> <span class="img_inline" style="margin: 0px;color: inherit; font-family: cairo; margin-top: 0px; margin-bottom: 0px; word-break: break-word; font-size: 16px; line-height: 100%; clear: both;" data-mce-style="color: inherit; font-family: cairo; margin-top: 0px; margin-bottom: 0px; word-break: break-word; font-size: 16px; line-height: 100%; clear: both;"><img src="http://192.168.1.53/rabt/backend/assets/images/mail/img/bgiimg.png" alt="bgilogo.png" style="-ms-interpolation-mode: bicubic; border: 0; height: auto; line-height: 100%; outline: none; text-decoration: none;" data-mce-src="http://192.168.1.53/rabt/backend/assets/images/mail/img/bgiimg.png" data-mce-style="-ms-interpolation-mode: bicubic; border: 0; height: auto; line-height: 100%; outline: none; text-decoration: none;"></span>
                                                                                </p>
                                                                            </td>
                                                                        </tr>
                                                                    </tbody>
                                                                </table>
                                                            </div>
                                                        </td>
                                                    </tr>
                                                </tbody>
                                            </table>
                                        </div>
                                    </td>
                                </tr>
                        </tbody>
                    </table>
                </div>
            </td>
       </tr>
    </tbody>
</table></div></td></tr></table>