<meta charset="UTF-8">
<style>
@import url('https://fonts.googleapis.com/css2?family=arial:wght@400;500;750;750&display=swap');
	 .column_cell a:visited {
       color: #fff;
	 }
	 .column_cancel a:visited{
		color: #f71b02;
	 }
	 a,a:visited {
		color:#4ca0ab;
	 }
     .previewText{
        display:none !important;
     }
</style>


<table width="100%"  style="background:rgb(226, 234, 240) none repeat scroll 0% 0% / auto padding-box border-box;">
	<tbody>
        <tr>
            <td width="100%" align="center" style="text-align:center;background:rgb(226, 234, 240);margin:0 auto;width:100%;max-width: 100%;padding:0px 0 30px 0" data-mce-href="text-align:center;background:rgb(226, 234, 240);margin:0 auto;width:100%;max-width: 100%;padding:0px 0 30px 0">
            <div width="100%" align="center" style="text-align:center;background:rgb(226, 234, 240);margin:0 auto;width:100%;padding: 0px" data-mce-href="text-align:center;background:rgb(226, 234, 240);margin:0 auto;width:100%;padding:0px">
                <table>
                    <tbody>
                        <tr>
                            <td align="center" width="750" style="margin-top: 50px;max-width: 750px;text-align: center;width:750px; " data-mce-style="margin-top:50px;max-width: 750px;width:750px; text-align: center">
                                <!-- <span class="preheader" style="display: none;font-size: 16px;font-family: arial;padding-top: 30px; display:none!important;visibility:hidden;opacity:0;color:transparent;height:0;width:0;width: 750px;word-break: break-word;max-width:750px;" data-mce-style="display: none;font-size: 16px;font-family: arial;padding-top: 30px;display: none !important; visibility: hidden; opacity: 0; color: transparent; height: 0;max-width:750px;width: 750px;word-break: break-word;"><?= $preheadertext ?></span> -->
                                <!--*|IF:MC_PREVIEW_TEXT|*-->
                                <!--[if !gte mso 9]><!----><span class="previewText" style="display:none; font-size:0px; line-height:0px; max-height:0px; max-width:0px; opacity:0; overflow:hidden; visibility:hidden; mso-hide:all;"><?= $preheadertext ?></span><!--<![endif]-->
                                <!--*|END:IF|*-->
                            </td>
                        </tr>
                    </tbody>
                </table>
                    <table class="content_section mce-item-table" role="presentation" align="center" width="750" cellspacing="0" cellpadding="0" border="0" style="text-align:center; max-width: 750px; width: 750px; margin-left: auto; margin-right: auto; background-color: #E2EAF0; -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt;" data-mce-style="text-align:center;width:750px;max-width: 750px; margin-left: auto; margin-right: auto; background-color: #E2EAF0; -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt;">
                        <tbody>
                            <tr>
                                <td class="column_cell px py_xs text_right mobile_center" style="vertical-align: top; text-align: right; margin-bottom: 25px; margin-top: 25px; -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt; float: right; width: 50%; padding: 25px 0px 25px 0px;background-color: #E2EAF0; " data-mce-style="vertical-align: top; text-align: right; margin-bottom: 25px; margin-top: 25px; -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt; float: right; width: 50%; padding: 25px 0px 25px 0px;background-color: #E2EAF0; ">
                                    
                                    <?php if(!$view){  ?>
                                        <p class="text_secondary" style="color: #000; font-family: arial; margin-top: 0px; margin-bottom: 0px; word-break: break-word; font-size: 16px; line-height: 26px; margin-right: 20px;" data-mce-style="color: #000; font-family: arial; margin-top: 0px; margin-bottom: 0px; word-break: break-word; font-size: 13px; line-height: 26px; margin-right: 20px;">
                                            <a>&nbsp;&nbsp;&nbsp;</a>   
                                            <a href="<?= \Yii::$app->params['baseMailPath']."/ma/mail/sendmail".$queryparams."view=ar" ?>" style="-webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; text-decoration: underline; color: #4CA0AB; font-family: arial; margin-top: 0px; margin-bottom: 0px; word-break: break-word; font-size: 13px; line-height: 26px;" data-mce-href="<?= \Yii::$app->params['baseMailPath']."/ma/mail/sendmail".$queryparams."&view=ar" ?>" data-mce-style="-webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; text-decoration: underline; color: #4CA0AB !important; font-family: arial; margin-top: 0px; margin-bottom: 0px; word-break: break-word; font-size: 13px; line-height: 26px;">View in Arabic</a> 
                                            <a>&nbsp;&nbsp;&nbsp;</a>
                                            <a href="<?= \Yii::$app->params['baseMailPath']."/ma/mail/sendmail".$queryparams."view=en" ?>" style="-webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; text-decoration: underline; color: #4CA0AB; font-family: arial; margin-top: 0px; margin-bottom: 0px; word-break: break-word; font-size: 13px; line-height: 26px;" data-mce-href="<?= \Yii::$app->params['baseMailPath']."/ma/mail/sendmail".$queryparams."&view=en" ?>" data-mce-style="-webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; text-decoration: underline; color: #4CA0AB !important; font-family: arial; margin-top: 0px; margin-bottom: 0px; word-break: break-word; font-size: 13px; line-height: 26px;">View in browser</a> 
                                        </p>
                                    <?php } ?>
                                    
                                    <?php if($view == 'en'){  ?>
                                        <p class="text_secondary" style="color: #959ba0; font-family: arial; margin-top: 0px; margin-bottom: 0px; word-break: break-word; font-size: 16px; line-height: 26px; margin-right: 20px;" data-mce-style="color: #959ba0; font-family: arial; margin-top: 0px; margin-bottom: 0px; word-break: break-word; font-size: 16px; line-height: 26px; margin-right: 20px;"><a href="<?= \Yii::$app->params['baseMailPath']."/ma/mail/sendmail".$queryparams."view=ar" ?>" style="-webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; text-decoration: none; color: #0366d6; font-family: arial; margin-top: 0px; margin-bottom: 0px; word-break: break-word; font-size: 13px; line-height: 26px;" data-mce-href="<?= \Yii::$app->params['baseMailPath']."/ma/mail/sendmail".$queryparams."&view=ar" ?>" data-mce-style="-webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; text-decoration: none; color: #0366d6 !important; font-family: arial; margin-top: 0px; margin-bottom: 0px; word-break: break-word; font-size: 13px; line-height: 26px;">View in Arabic</a></p>
                                    <?php } ?>
                                         
                                    <?php if($view == 'ar'){  ?>
                                        <p class="text_secondary" style="color: #959ba0; font-family: arial; margin-top: 0px; margin-bottom: 0px; word-break: break-word; font-size: 16px; line-height: 26px; margin-right: 20px;" data-mce-style="color: #959ba0; font-family: arial; margin-top: 0px; margin-bottom: 0px; word-break: break-word; font-size: 16px; line-height: 26px; margin-right: 20px;"><a href="<?= \Yii::$app->params['baseMailPath']."/ma/mail/sendmail".$queryparams."view=en" ?>" style="-webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; text-decoration: none; color: #0366d6; font-family: arial; margin-top: 0px; margin-bottom: 0px; word-break: break-word; font-size: 13px; line-height: 26px;" data-mce-href="<?= \Yii::$app->params['baseMailPath']."/ma/mail/sendmail".$queryparams."&view=en" ?>" data-mce-style="-webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; text-decoration: none; color: #0366d6 !important; font-family: arial; margin-top: 0px; margin-bottom: 0px; word-break: break-word; font-size: 13px; line-height: 26px;">View in English</a></p>
                                    <?php } ?>
                                
                                </td>
                            </tr>
                                <tr>
                                    <td class="content_cell bg_white brounded bt_primary px py_md" style="font-size: 0; text-align: center; border-bottom: 1px solid #dadada; background-color: #f7f7f7; border-top: 4px solid #4ca0ab; border-radius: 4px; -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt; padding: 10px 0px 10px 0px;" data-mce-style="font-size: 0; text-align: center; border-bottom: 1px solid #dadada; background-color: #f7f7f7; border-top: 4px solid #4ca0ab; border-radius: 4px; -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt; padding: 10px 0px 10px 0px;">
                                        <div style="background: #f7f7f7;" data-mce-style="background: #f7f7f7;">
                                            <table class="column_row mce-item-table" style="font-size: 0; text-align: center; max-width: 100%; margin-left: 0; margin-right: 0; width: 100%;" data-mce-style="font-size: 0; text-align: center; max-width: 100%; margin-left: 0; margin-right: 0; width: 100%;">
                                                <tbody>
                                                    <tr style="display: flex; align-items: center; justify-content:space-evenly;" data-mce-style="display: flex; align-items: center; justify-content:space-evenly;">
                                                        <td class="column_cell px py_xs text_primary text_left mobile_center" style="vertical-align: top;  text-align: center;-webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt; padding: 10px 0px 10px 0px;" data-mce-style="vertical-align: top; text-align: center; -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt; padding: 25px 0px 25px 0px;"><img src="<?= \Yii::$app->params['APP_URL'] ?>backend/assets/images/mail/img/newheaderrabtlogo.png" alt="rabtlogo" style="-ms-interpolation-mode: bicubic; border: 0; height: auto; line-height: 100%; outline: none; text-decoration: none;" data-mce-src="<?= \Yii::$app->params['APP_URL'] ?>backend/assets/images/mail/img/newheaderrabtlogo.png" data-mce-style="-ms-interpolation-mode: bicubic; border: 0; height: auto; line-height: 100%; outline: none; text-decoration: none;"></td>
                                                    </tr>
                                                </tbody>
                                            </table>
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td align="center" class="content_cell bg_white brounded bt_primary px py_md" style="font-size: 0; text-align: center; border-bottom: 1px solid #dadada; background-color: #ffffff; border-top: 1px solid #e2eaf0; border-radius: 4px; -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt; " data-mce-style="font-size: 0; text-align: center; border-bottom: 1px solid #dadada; background-color: #ffffff; border-top: 1px solid #e2eaf0; border-radius: 4px; -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt; ">
                                      
                                        <!-- Body content -->
                                            <?= $content ?>

                                                    <tr>
                                                        <td align="center" class="content_cell" style=" background-color: #f9f9f9; font-size: 0; text-align: center; -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt;" data-mce-style="background-color: #f9f9f9; font-size: 0; text-align: center; -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt;">
                                                            <div class="column_row" style="font-size: 0; text-align: center; max-width: 100%; margin: 0 auto;" data-mce-style="font-size: 0; text-align: center; max-width: 100%px; margin: 0 auto;">
                                                                <table class="column mce-item-table" role="presentation" align="center" width="100%" cellspacing="0" cellpadding="0" border="0" style="margin-top: 20px; vertical-align: top; -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt;" data-mce-style="margin-top: 20px;vertical-align: top; -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt;">
                                                                    <tbody>
                                                                        <tr>
                                                                            <td class="column_cell px py_xs text_primary text_left mobile_center" style="margin-left: 20px; vertical-align: top; color: #2376dc; text-align: left; -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt; float: left; width: 60%; padding: 20px 20px;" data-mce-style="margin-left: 20px; vertical-align: top; color: #2376dc; text-align: left; -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt; float: left; width: 60%; padding: 20px 20px;">
                                                                                <img src="<?= \Yii::$app->params['APP_URL'] ?>backend/assets/images/mail/img/newrabtfootlogo.png" alt="rabtlogo" style="-ms-interpolation-mode: bicubic; border: 0; height: auto; line-height: 100%; outline: none; text-decoration: none;" data-mce-src="<?= \Yii::$app->params['APP_URL'] ?>backend/assets/images/mail/img/newrabtfootlogo.png" data-mce-style="-ms-interpolation-mode: bicubic; border: 0; height: auto; line-height: 100%; outline: none; text-decoration: none;">
                                                                            </td>
                                                                            <td class="column_cell px py_xs text_right mobile_center" style="padding-right: 10px; vertical-align: top; text-align: left; -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt; float: right; width: 29%;padding: 20px 10px;" data-mce-style="padding-right: 10px;vertical-align: top; text-align: left; -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt; float: right; width: 29%; padding: 20px 10px;">
                                                                                <p class="text_link text_xs" style="color: #333; font-family: arial; margin-top: 0px; margin-bottom: 5px; word-break: break-word; font-size: 16px; line-height: 13px;" data-mce-style="color: #333; font-family: arial; margin-top: 0px; margin-bottom: 5px; word-break: break-word; font-size: 16px; line-height: 13px;"><span style="color: #333; text-decoration: none;font-weight:bold; " data-mce-style="color: #333; text-decoration: none;font-weight:bold;">Address Info</span></p>
                                                                                <p class="text_link text_xs" style="color: #333; font-family: arial; margin-top: 0px; margin-bottom: 5px; word-break: break-word; font-size: 14px;line-height: 20px;" data-mce-style="color: #333; font-family: arial; margin-top: 0px; margin-bottom: 5px; word-break: break-word; font-size: 14px line-height: 20px;"><span style="color: #333; text-decoration: none;" data-mce-style="color: #333; text-decoration: none;">Industrial Innovation Academy (IIA)<br> 124, 65, Rusayl Industrial City,<br>Al Rusail, Al Seeb,<br>Muscat, Sultanate of Oman.</span>
                                                                                </p>
                                                                            </td>
                                                                        </tr>
                                                                    </tbody>
                                                                </table>
                                                                <!-- <table class="column mce-item-table" role="presentation" align="center" width="100%" cellspacing="0" cellpadding="0" border="0" style=" vertical-align: top; -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt;" data-mce-style="padding: 20px 10px;vertical-align: top; -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt;">

                                                                    <tbody>
                                                                        <tr>
                                                                            <td align="center" width="100%" style="width: 100%;max-width: 100%; text-align: center; padding-bottom: 10px;" data-mce-style="width: 100%;max-width: 100%;text-align:center; padding-bottom: 10px;">
                                                                                <p style="font-family: arial; font-style: normal;word-break: break-word; line-height: 20px;margin-bottom: 10px; text-align: center;" data-mce-style="font-family: arial;font-style: normal;color: #333333; font-family: arial; word-break: break-word; font-size: 16px; line-height: 20px; margin-bottom: 10px; text-align: center;font-style: normal;font-size: 15px;">
                                                                                    <span style="font-family: arial;font-style: normal;font-size: 14px; color: #333333; font-family: arial;" data-mce-style="font-family: arial;font-style: normal;font-size: 14px; color: #333333; font-family: arial;">
                                                                                        The Digital Platform for Oman’s Industrial Sector
                                                                                </span>
                                                                                </p>
                                                                                <p class="img_inline mb" style="color: inherit; font-family: arial; margin-top: 0px; margin-bottom: 16px; word-break: break-word; font-size: 16px; line-height: 100%; clear: both;" data-mce-style="color: inherit; font-family: arial; margin-top: 0px; margin-bottom: 16px; word-break: break-word; font-size: 16px; line-height: 100%; clear: both;">
                                                                                    <a href="#" style="-webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; text-decoration: none; color: #959ba0; font-family: arial; margin-top: 0px; margin-bottom: 0px; word-break: break-word;" data-mce-href="#" data-mce-style="-webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; text-decoration: none; color: #959ba0; font-family: arial; margin-top: 0px; margin-bottom: 0px; word-break: break-word;"><img src="<?= \Yii::$app->params['APP_URL'] ?>backend/assets/images/mail/img/whatsapp.png" width="24" height="24" alt="whatsapp" style="max-width: 24px; -ms-interpolation-mode: bicubic; border: 0; height: auto; line-height: 100%; outline: none; text-decoration: none;" data-mce-src="<?= \Yii::$app->params['APP_URL'] ?>backend/assets/images/mail/img/whatsapp.png" data-mce-style="max-width: 24px; -ms-interpolation-mode: bicubic; border: 0; height: auto; line-height: 100%; outline: none; text-decoration: none;"></a>&nbsp;
                                                                                    <a href="#" style="-webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; text-decoration: none; color: #959ba0; font-family: arial; margin-top: 0px; margin-bottom: 0px; word-break: break-word;" data-mce-href="#" data-mce-style="-webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; text-decoration: none; color: #959ba0; font-family: arial; margin-top: 0px; margin-bottom: 0px; word-break: break-word;"><img src="<?= \Yii::$app->params['APP_URL'] ?>backend/assets/images/mail/img/facebook.png" width="24" height="24" alt="facebook" style="max-width: 24px; -ms-interpolation-mode: bicubic; border: 0; height: auto; line-height: 100%; outline: none; text-decoration: none;" data-mce-src="<?= \Yii::$app->params['APP_URL'] ?>backend/assets/images/mail/img/facebook.png" data-mce-style="max-width: 24px; -ms-interpolation-mode: bicubic; border: 0; height: auto; line-height: 100%; outline: none; text-decoration: none;"></a>&nbsp; 
                                                                                    <a href="#" style="-webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; text-decoration: none; color: #959ba0; font-family: arial; margin-top: 0px; margin-bottom: 0px; word-break: break-word;" data-mce-href="#" data-mce-style="-webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; text-decoration: none; color: #959ba0; font-family: arial; margin-top: 0px; margin-bottom: 0px; word-break: break-word;"><img src="<?= \Yii::$app->params['APP_URL'] ?>backend/assets/images/mail/img/twitter.png" width="24" height="24" alt="Youtube" style="max-width: 24px; -ms-interpolation-mode: bicubic; border: 0; height: auto; line-height: 100%; outline: none; text-decoration: none;" data-mce-src="<?= \Yii::$app->params['APP_URL'] ?>backend/assets/images/mail/img/twitter.png" data-mce-style="max-width: 24px; -ms-interpolation-mode: bicubic; border: 0; height: auto; line-height: 100%; outline: none; text-decoration: none;"></a>&nbsp; 
                                                                                    <a href="#" style="-webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; text-decoration: none; color: #959ba0; font-family: arial; margin-top: 0px; margin-bottom: 0px; word-break: break-word;" data-mce-href="#" data-mce-style="-webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; text-decoration: none; color: #959ba0; font-family: arial; margin-top: 0px; margin-bottom: 0px; word-break: break-word;"><img src="<?= \Yii::$app->params['APP_URL'] ?>backend/assets/images/mail/img/youtube.png" width="24" height="24" alt="linkedin" style="max-width: 24px; -ms-interpolation-mode: bicubic; border: 0; height: auto; line-height: 100%; outline: none; text-decoration: none;" data-mce-src="<?= \Yii::$app->params['APP_URL'] ?>backend/assets/images/mail/img/youtube.png" data-mce-style="max-width: 24px; -ms-interpolation-mode: bicubic; border: 0; height: auto; line-height: 100%; outline: none; text-decoration: none;"></a>&nbsp;
                                                                                    <a href="#" style="-webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; text-decoration: none; color: #959ba0; font-family: arial; margin-top: 0px; margin-bottom: 0px; word-break: break-word;" data-mce-href="#" data-mce-style="-webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; text-decoration: none; color: #959ba0; font-family: arial; margin-top: 0px; margin-bottom: 0px; word-break: break-word;"><img src="<?= \Yii::$app->params['APP_URL'] ?>backend/assets/images/mail/img/linkdin.png" width="24" height="24" alt="twitter" style="max-width: 24px; -ms-interpolation-mode: bicubic; border: 0; height: auto; line-height: 100%; outline: none; text-decoration: none;" data-mce-src="<?= \Yii::$app->params['APP_URL'] ?>backend/assets/images/mail/img/linkdin.png" data-mce-style="max-width: 24px; -ms-interpolation-mode: bicubic; border: 0; height: auto; line-height: 100%; outline: none; text-decoration: none;"></a>&nbsp;
                                                                                </p>
                                                                            </td>
                                                                        </tr>
                                                                    </tbody>
                                                                </table> -->
                                                                <table class="content_section mce-item-table" role="presentation" align="center" width="100%" cellspacing="0" cellpadding="0" border="0" style="padding: 15px 0; margin-left: auto; margin-right: auto; background-color: #e6e6e6;-webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt;" data-mce-style="padding: 15px 0;margin-left: auto; margin-right: auto; background-color: #e6e6e6;-webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt;">
                                                                    <tbody>
                                                                        <tr>
                                                                            <td class="column_cell px py_xs text_right mobile_center" style=" vertical-align: top; text-align: left; -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt; float: left; width: 57%; padding: 15px 0 15px 10px;" data-mce-style="vertical-align: top; text-align: left; -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt; float: left; width: 57%; padding: 15px 0 15px 10px;">
                                                                                <p class="mb_xs" style="margin-top: 15px;color: #333; font-family: arial; margin-bottom: 0px; word-break: break-word; font-size: 13px; line-height: 26px;" data-mce-style="margin-top: 15px;color: #333; font-family: arial; margin-bottom: 0px; word-break: break-word; font-size: 13px; line-height: 26px;">© <?= date("Y") ?> Industrial Innovation Academy. All Rights Reserved</p>
                                                                            </td>
                                                                            <td nowrap class="column_cell px py_xs text_right mobile_center" style="vertical-align: top; text-align: left; -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt;  width: 12%; padding: 14px 0;" data-mce-style="vertical-align: top; text-align: right; -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt; float: left; width: 12%; padding: 15px 0;">
                                                                                <p class="mb_xs" style="margin-top: 15px;color: #333; font-family: arial; margin-bottom: 0px; word-break: break-word; font-size: 13px; line-height: 26px;" data-mce-style="margin-top: 14px;color: #333; font-family: arial; margin-bottom: 0px; word-break: break-word; font-size: 13px; line-height: 26px;">Implemented by &nbsp;</p>
                                                                            </td>
                                                                            <td class="column_cell px py_xs text_primary text_left mobile_center" style=" vertical-align: top; color: #333; text-align: left; -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 27%; padding: 15px 10px 15px 0;" data-mce-style="vertical-align: top; color: #333; text-align: left; -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; mso-table-lspace: 0pt; mso-table-rspace: 0pt; float: right; width: 27%; padding:15px 10px 15px 0;">
                                                                            <p style="margin: 0px;"> <span class="img_inline" style="margin: 0px;color: inherit; font-family: arial; margin-top: 0px; margin-bottom: 0px; word-break: break-word; font-size: 16px; line-height: 100%; clear: both;" data-mce-style="color: inherit; font-family: arial; margin-top: 0px; margin-bottom: 0px; word-break: break-word; font-size: 16px; line-height: 100%; clear: both;"><img src="<?= \Yii::$app->params['APP_URL'] ?>backend/assets/images/mail/img/bgiimg.png" alt="bgilogo.png" style="-ms-interpolation-mode: bicubic; border: 0; height: auto; line-height: 100%; outline: none; text-decoration: none;" data-mce-src="<?= \Yii::$app->params['APP_URL'] ?>backend/assets/images/mail/img/bgiimg.png" data-mce-style="-ms-interpolation-mode: bicubic; border: 0; height: auto; line-height: 100%; outline: none; text-decoration: none;"></span>
                                                                                </p>
                                                                            </td>
                                                                        </tr>
                                                                    </tbody>
                                                                </table>
                                                            </div>
                                                        </td>
                                                    </tr>
                                                </tbody>
                                            </table>
                                        </div>
                                    </td>
                                </tr>
                        </tbody>
                    </table>
                </div>
            </td>
       </tr>
    </tbody>
</table>